---
development:
  cloud_name: speech-tastic
  api_key:
  api_secret:
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: speech-tastic
  api_key:
  api_secret:
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: speech-tastic
  api_key:
  api_secret:
  enhance_image_tag: true
  static_image_support: false